--Table Descriptions :

Create Table ZONE_MST(

ZON_CODE varchar(1),
ZON_DESC varchar(20),
ZON_STATUS varchar(1),
ZON_START date,
ZON_END date,
ZON_REGIONS int,

Constraint PK_ZON_CODE PRIMARY KEY (ZON_CODE),
Constraint Invalid_Zon_Status CHECK (ZON_STATUS in ('Y','N')),
Constraint Max_Zon_Regions CHECK(ZON_REGIONS <= 99)
);

--REGION_MST
Create table REGION_MST
(

RGN_CODE varchar(3),
RGN_DESC varchar(20),
RGN_ZON_CODE varchar(1),
RGN_STATUS varchar(1),
RGN_START date,
RGN_END date,
RGN_DEPOTS int,

Constraint PK_RGN_CODE PRIMARY KEY (RGN_CODE),
Constraint FK_RGN_ZON_CODE FOREIGN KEY (RGN_ZON_CODE)
    REFERENCES ZONE_MST (ZON_CODE) ON DELETE CASCADE,
Constraint MAX_RGN_DEPOTS CHECK (RGN_DEPOTS <= 99),
Constraint RGN_INVALID_STATUS CHECK(RGN_STATUS in ('Y','N'))
);

--DEPOT_MST

Create table DEPOT_MST
(
DPT_CODE varchar(3),
DPT_DESC varchar(50),
DPT_RGN_CODE varchar(3),
DPT_STATUS varchar(1),
DPT_START date,
DPT_END date,

Constraint PK_DPT_CODE PRIMARY KEY (DPT_CODE),
Constraint FK_DPT_RGN_CODE FOREIGN KEY (DPT_RGN_CODE) 
REFERENCES REGION_MST(RGN_CODE) ON DELETE CASCADE,
Constraint DPT_INVALID_STATUS CHECK(DPT_STATUS in ('Y','N'))
);

Create table PROD_LINE_MST
(
PL_CODE varchar(3),
PL_DESC varchar(255),
PL_WD_MARGIN Number(8,2),
PL_RET_MARGIN number(8,2),

Constraint PK_PL_CODE PRIMARY Key (PL_CODE)
);

Create table PROD_SIZE_MST
(
PS_CODE varchar(3),
PS_DESC varchar(255),

Constraint PK_PS_CODE PRIMARY KEY (PS_CODE)
);

Create table PROD_CATG_MST
(
CT_CODE varchar(3),
CT_DESC Varchar(255),
CT_PL_CODE varchar(3),

Constraint CK_CT_CODE_AND_CT_PL_CODE PRIMARY KEY (CT_CODE,CT_PL_CODE),
Constraint FK_CT_PL_CODE FOREIGN KEY (CT_PL_CODE) REFERENCES PROD_LINE_MST(PL_CODE)
);

Create table PROD_MST
(
PR_CODE varchar(3),
PR_DESC varchar(255),
PR_CT_CODE varchar(3),
PR_PL_CODE varchar(3),
PR_PS_CODE varchar(3),
PR_SIZE INTEGER,
PR_RATE NUMBER(5,2),

Constraint PK_PR_CODE PRIMARY KEY (PR_CODE),
Constraint FCK_PR_CT_CODE FOREIGN KEY (PR_CT_CODE, PR_PL_CODE)
    REFERENCES PROD_CATG_MST (CT_CODE, CT_PL_CODE),
CONSTRAINT FK_PR_PS_CODE FOREIGN KEY (PR_PS_CODE)
    REFERENCES PROD_SIZE_MST (PS_CODE)
);

Create table PROD_DEPOT_ALLOC
(
PD_DPT_CODE varchar(3),
PD_PR_CODE varchar(3),

Constraint CK_PD_DPT_CODE_AND_PD_PR_CODE PRIMARY KEY (PD_DPT_CODE,PD_PR_CODE),
Constraint FK_PD_DPT_CODE FOREIGN KEY (PD_DPT_CODE) 
    REFERENCES DEPOT_MST(DPT_CODE),
Constraint FK_PD_PR_CODE FOREIGN KEY (PD_PR_CODE)
    REFERENCES PROD_MST(PR_CODE)
);

Create table WD_MST
(
WD_CODE varchar(3),
WD_DESC varchar(255),
WD_DPT_CODE varchar(3),
WD_CONT_START date,
WD_cont_end date,
WD_CONT_RENEWAL date,
WD_ACTUAL_BG number(6,2),
WD_UTZ_BG number(6,2),
WD_STATUS varchar(1),

Constraint PK_WD_CODE PRIMARY KEY (WD_CODE),
Constraint FK_WD_DPT_CODE FOREIGN KEY (WD_DPT_CODE)
    REFERENCES DEPOT_MST(DPT_CODE)
);

Create table WD_STATUS_TXN
(
WT_WD_CODE varchar(3),
WT_WD_TXN_NO varchar(10),
WT_WD_STATUS varchar(1),
WT_START_DATE date,
WT_END_DATE date,

Constraint CK_WT_WD_CODE_AND_WD_TXN_NO PRIMARY KEY (WT_WD_CODE,WT_WD_TXN_NO),
Constraint FK_WT_WD_CODE FOREIGN KEY (WT_WD_CODE)
    REFERENCES WD_MST(WD_CODE)
);

Create table PROD_WD_ALLOC
(
PW_WD_CODE varchar(3),
PW_PR_CODE varchar(3),
PW_DPT_CODE varchar(3),
PW_CURR_YEAR_TARGET INTEGER,
PW_CUMM_TARGET_ACHIEVED INTEGER,

Constraint CK_PW_WD_CODE_AND_PR_CODE PRIMARY KEY (PW_WD_CODE,PW_PR_CODE),
Constraint FK_PW_PR_CODE FOREIGN KEY (PW_PR_CODE)
    REFERENCES PROD_MST(PR_CODE),
Constraint FK_PW_WD_CODE FOREIGN KEY (PW_WD_CODE)
    REFERENCES WD_MST(WD_CODE),
Constraint FK_PW_DPT_CODE FOREIGN KEY (PW_DPT_CODE)
    REFERENCES DEPOT_MST(DPT_CODE)
);

Create table WD_MONTHLY_SALES
(
WM_WD_CODE varchar(3),
WM_PR_CODE varchar(3),
WM_YRMTH date,
WM_SALE_QTY integer,
WM_SALE_VALUE number(6,2),

    Constraint CK_WM_WDCODE_N_PRCODE_N_YRMTH PRIMARY KEY (WM_WD_CODE,WM_PR_CODE,WM_YRMTH),
Constraint FCK_WM_WD_CODE FOREIGN KEY (WM_WD_CODE,WM_PR_CODE)
    REFERENCES PROD_WD_ALLOC(PW_WD_CODE,PW_PR_CODE)
);

Create table WD_DAILY_SALES
(
WS_WD_CODE varchar(3),
WS_PR_CODE varchar(3),
WS_SALE_DATE date,
WS_SALE_QTY integer,
WD_SALE_RATE number(5,2),

Constraint CK_WS_WDCODE_N_PRCODE_N_SALEDT PRIMARY KEY (WS_WD_CODE, WS_PR_CODE, WS_SALE_DATE),
Constraint FCK_WDCODE_N_PRCODE FOREIGN KEY (WS_WD_CODE,WS_PR_CODE)
    REFERENCES PROD_WD_ALLOC(PW_WD_CODE,PW_PR_CODE)
);